### PR TITLE
Fix python version compatibility issue

### PR DESCRIPTION
**Pull request by AndyGrant**
The Empty fields like "{}".format('Test') do not work for some versions of python. 

If you have python version 2, you must have 2.7+
If you have python version 3, you must have 3.0+

### CODE REVIEW

**Comment by lucasart** [comment]
Thanks. But I only plan to support Python 2.7, and Python 3. Is this necessary for Python 2.7 ?

**Comment by AndyGrant** [comment]
My original message had a mistake. It should have read:

If you have python version 3, you must have 3.1+

This way of formatting will not work for the following versions:

Anything below python 2.7
Anything between python 3.0 and python 3.1

**Comment by AndyGrant** [comment]
From the python 3.0 docs...

replacement_field ::=  "{" field_name ["!" conversion] [":" format_spec] "}"

Where as for python3.1+ or python2.7 it says...

replacement_field ::=  "{" [field_name] ["!" conversion] [":" format_spec] "}"

https://docs.python.org/release/3.0/library/string.html#format-string-syntax
https://docs.python.org/2.7/library/string.html#format-string-syntax

**Comment by lucasart** [comment]
ok, i'll merge this, for Python 3.0 compatibility. thanks.

**Pull request closed without merging**
