### PR TITLE
Add GamePool, resolves 'rework the concurrency model'

### PR DESCRIPTION
**Pull request by AndyGrant**
Not sure if you are looking for help with this, but if you are, I took a shot at resolving one of your posted issues. Tested out my changes on a Windows7-64bit machine and an Ubuntu-32bit machine and was able to run multiple games concurrently, without ever closing the engines down.

### CODE REVIEW

**Comment by AndyGrant** [comment]
I have a working version using multiprocessing instead of threading, if that is what you are looking for. Although I don't know if the functionality of 'def play' really needs to be split into different processes and not just different threads.

**Comment by lucasart** [comment]
threads are fine, and indeed the more natural choice. there was no reason to use processes, other than lazyness: that's what multiprocessing.Pool() does. my intent was to write a proper thread pool eventually.

**Comment by lucasart** [comment]
I merged your patch here d8287c4e. I changed things a little bit, to adapt to the new code organization.

**Comment by AndyGrant** [comment]
If you want to be able to handle Keyboard Interrupts in a way that kills all threads and prints data based on the tests that have already been run its either going to be a platform dependent solution or you will have to turn play_game into an extension of a Thread which regularly checks its alive status. If you instead use a Process, you can terminate them on KB Interrupts.

**Comment by lucasart** [comment]
Let me try something simple first. If that fails, I'll do it your way.

**Comment by AndyGrant** [comment]
Sounds good. Submitted my changes just as you sent this. If you find a clean way of doing it with Threads, use them by all means.

**Pull request closed without merging**
